before:
  hooks:
    - go mod download
    #- go generate ./...

# github_urls:
#   api: https://github.com/api/v3/
#   upload: https://github.com/api/uploads/
#   download: https://github.com/
#   skip_tls_verify: false
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    binary: goyaml
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64

archives:
  - replacements:
      amd64: x86_64
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: theochva
      name: homebrew-grizano
    name: goyaml
    folder: Formula
    description: Utility for performing simple operations on a YAML file.
    homepage: https://github.com/theochva/goyaml
    test: |
      system "#{bin}/goyaml --version"
    url_template: "https://github.com/theochva/goyaml/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CustomGitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: "./download_strategies/custom_download_strategy"
    install: |
      bin.install "goyaml"
